name: Create Tag and Release

on:
  push:
    # Trigger the action when pushing a tag.
    tags:
      - 'v*'  # This means the action is triggered for tags like v1.0, v2.0, etc.
  workflow_dispatch:  # Allows manual trigger from GitHub UI
  
jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Set up Git for release
      run: |
        git config user.name "devendraappa"
        git config user.email "devendraappa.kune@gmail.com"

    - name: Create a new tag
      run: |
        NEW_TAG=$(date +'%Y%m%d%H%M%S')  # Example tag format
        echo "New Tag: $NEW_TAG"
        git tag -a "$NEW_TAG" -m "Automated tag creation"
        git push origin "$NEW_TAG"
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
    
    - name: Create a GitHub release
      run: |
        curl -X POST \
          -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
          -d '{"tag_name": "$NEW_TAG", "name": "Release $NEW_TAG", "body": "Automated release for version $NEW_TAG"}' \
          "https://api.github.com/repos/${{ github.repository }}/releases"
