name: Create Tag and Release

on:
  push:
    tags:
      - 'v*'  # Trigger when a tag matching v* is pushed (like v1.0.2, v1.1.0, etc.)

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Set up Git for release
      run: |
        git config user.name "devendraappa"
        git config user.email "devendraappa.kune@gmail.com"

    - name: Create a new tag
      id: tag
      run: |
        # Generate a new tag with the format v1.0.2-YYYYMMDD
        VERSION="v1.0.2"
        DATE=$(date +'%Y%m%d')
        NEW_TAG="${VERSION}-${DATE}"
        echo "New tag created: $NEW_TAG"
        git tag -a "$NEW_TAG" -m "Automated tag creation for $NEW_TAG"
        git push origin "$NEW_TAG"
        echo "::set-output name=tag_name::$NEW_TAG"
      
    - name: Create a GitHub release
      run: |
        # Get the tag name from the previous step's output
        TAG_NAME="${{ steps.tag.outputs.tag_name }}"
        echo "Creating release for tag: $TAG_NAME"
        curl -X POST \
          -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
          -d "{
            \"tag_name\": \"$TAG_NAME\",
            \"name\": \"Release $TAG_NAME\",
            \"body\": \"Automated release for version $TAG_NAME\",
            \"draft\": false,
            \"prerelease\": false
          }" \
          "https://api.github.com/repos/${{ github.repository }}/releases"
        
