name: Release Workflow

on:
  push:
    tags:
      - "v*.*" # Trigger on tags like v1.0.0, v2.1.3, etc.

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Create a GitHub Release
      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Required to authenticate with GitHub
        with:
          tag_name: ${{ github.ref_name }} # Use the pushed tag name
          release_name: Release ${{ github.ref_name }} # Name the release based on the tag
          body: "Release notes for version ${{ github.ref_name }}" # Release notes
          draft: false
          prerelease: false 
